### ISSUE TITLE
Gene annotator doesn't seem to be working—PyEnsembl

### ISSUE THREAD

**Issue by ihodes** [hammerlab/cycledash#672]
```
Traceback (most recent call last):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/cycledash/cycledash/workers/gene_annotator.py", line 43, in annotate
    EnsemblRelease(config.ENSEMBL_RELEASE).install()  # Only runs the first time for this release.
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/ensembl_release.py", line 152, in install
    self._index(force=False)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/ensembl_release.py", line 163, in _index
    if self.db.create(force=force):
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 514, in create
    self._create_database(force=force)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/pyensembl/database.py", line 185, in _create_database
    version=DATABASE_SCHEMA_VERSION)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/datacache/database_helpers.py", line 200, in db_from_dataframes
    version=version)
  File "/home/cycledash/cycledash/venv/lib/python2.7/site-packages/datacache/database_helpers.py", line 100, in _create_cached_db
    db.drop_tables()
AttributeError: 'Database' object has no attribute 'drop_tables'
```

We're running `pyensembl==0.5.13`—newest version is `0.6.8`.

**Comment by ihodes** [comment]
This is working locally with 0.5.13, so I'm not entirely sure what the issue is.

**Comment by tavinathanson** [comment]
Seems like CycleDash doesn't have the latest version of `datacache` (and `pyensembl` doesn't require the latest version of `datacache`: https://github.com/hammerlab/pyensembl/blob/master/setup.py).

This is this: https://github.com/hammerlab/datacache/pull/21/files

**Comment by ihodes** [comment]
Related? https://github.com/hammerlab/cycledash/issues/562

**Comment by tavinathanson** [comment]
@ihodes Nah, that one looks like a `datacache` version mismatch, since at one point datacache had a `.db` and now it doesn't

**Comment by ihodes** [comment]
Isn't this one also a datacache version mismatch? ("Seems like CycleDash doesn't have the latest version of datacache")

**Comment by tavinathanson** [comment]
@ihodes Fair enough, though they're different mismatches

**Comment by ihodes** [comment]
But hopefully both fixed by updating PyEnsemble?

**Comment by tavinathanson** [comment]
I'm getting a bit confused about the versioning, but in short: datacache 0.4.13 is where the original issue gets fixed, and PyEnsembl still does not pull that in: so updating PyEnsembl in CycleDash won't fix that bug until PyEnsembl itself is updated. (Not sure about the latter issue.) Will make a PR now.
